name: Update Subscription

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - run: pip install -r requirements.txt

    - run: python parser.py

    - name: Push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

        git add .
        git commit -m "update" || exit 0
        git push
